# Recompensas do dia 1 ao 31 do check-in aura
dia_1: "diamond 1"
dia_2: "netherite_ingot 1"
dia_3: "experience_bottle 64"
dia_4: "gold_ingot 16"
dia_5: "iron_ingot 32"
dia_6: "diamond 2"
dia_7: "netherite_ingot 2"
dia_8: "experience_bottle 128"
dia_9: "gold_block 2"
dia_10: "diamond 5"
dia_11: "emerald 16"
dia_12: "netherite_ingot 3"
dia_13: "experience_bottle 256"
dia_14: "diamond 8"
dia_15: "iron_block 8"
dia_16: "netherite_ingot 4"
dia_17: "gold_block 8"
dia_18: "diamond 12"
dia_19: "emerald 32"
dia_20: "netherite_scrap 8"
dia_21: "experience_bottle 512"
dia_22: "diamond 16"
dia_23: "iron_block 16"
dia_24: "gold_block 16"
dia_25: "netherite_ingot 5"
dia_26: "diamond 24"
dia_27: "emerald 64"
dia_28: "netherite_scrap 16"
dia_29: "diamond 32"
dia_30: "netherite_ingot 8"
dia_31: "netherite_block 1"

