name: MinigameAura
version: 2.0.1
author: CM_FX
main: com.serpens.checkin.Checkin
api-version: "1.21"
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0
commands:
  checkin:
    description: abre o check-in diario
    usage: /checkin
    aliases: [diario, check]
